version: '3.6'

services:
  localstack:
    environment:
      AWS_ACCESS_KEY_ID: missing
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: missing
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sns,sqs
      VIRTUAL_HOST: localstack.messaging.localtest.me
      VIRTUAL_PORT: 8080
    image: localstack/localstack
    networks:
      - default
      - messaging

  rabbitmq:
    environment:
      VIRTUAL_HOST: rabbitmq.messaging.localtest.me
      VIRTUAL_PORT: 15672
    image: rabbitmq:3.7-management-alpine
    hostname: iris-rabbitmq
    networks:
      messaging:
        aliases:
          - iris-rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  messaging:
    build: docker/development
    depends_on:
      - localstack
      - rabbitmq
    environment:
      APP_NAME: messaging-services
      AWS_ACCESS_KEY_ID: missing
      AWS_ACCOUNT_ID: 123456789012
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: missing
      NODE_PATH: /var/task/src:/var/task/test
      SNS_ENDPOINT: http://localstack:4575
      SQS_ENDPOINT: http://localstack:4576
    container_name: iris-messenger
    networks:
      - default
      - messaging
    volumes:
      - .:/var/task

  proxy:
    image: jwilder/nginx-proxy
    networks:
      - messaging
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


networks:
  messaging:
    external: true

volumes:
  rabbitmq: